baseURL = "https://brecha-salarial.datasketch.co/"
languageCode = "es"
title = "Prejuicio e inequidad salarial entre hombres y mujeres de la salud"
taxonomies = []
publishDir = "docs"
# googleAnalytics = ""
