baseURL = "http://www.cuestionpublica.com/desigualdad-salarial-de-genero-en-sector-salud-colombia/"
languageCode = "es"
title = "Prejuicio e inequidad salarial entre hombres y mujeres de la salud"
description = "Datasketch y Cuestión Pública analizaron 331.757 contratos de hospitales estatales para determinar la desigualdad salarial entre hombres y mujeres en el sector de la salud en Colombia y encontramos que por cada $10.000 pesos que gana un hombre una mujer gana $6.100. La paridad de género sigue siendo una deuda en el sector público y privado en el país."
images = ["https://res.cloudinary.com/randommonkey/image/upload/v1600906694/brecha-salarial/main-bg.jpg"]
taxonomies = []
publishDir = "docs-cp"
# googleAnalytics = ""
