baseURL = "http://www.cuestionpublica.com/desigualdad-salarial-de-genero-en-sector-salud-colombia/"
languageCode = "es"
title = "Prejuicio e inequidad salarial entre hombres y mujeres de la salud"
taxonomies = []
publishDir = "docs-cp"
googleAnalytics = "UA-115081321-1"
